"""
Django settings for webgraph project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

SECRET_KEY = 'slug key'

# Application definition

INSTALLED_APPS = (
    'webgraph',
)

MIDDLEWARE_CLASSES = ()

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'django',
        'USER': 'django',
        'PASSWORD': 'slug password',
        'TEST': {
            'NAME': 'test',
        },
    }
}
